services:
  astro-install:
    image: rodamianro/util:astro-install
    build: 
      context: .
      target: install
    volumes:
     - ./:/init:rw
    networks:
      - astro-net

  astro-app:
    image: rodamianro/util:astro-app
    build: 
      context: .
      target: ${ENVIRONMENT}
    volumes:
     - ./astrobuild.tips:/app
    ports:
       - "80:4321"
    tty: true
    networks:
      - astro-net

networks:
  astro-net:
    driver: bridge

    
